settings:
  title: 'Status Page'
  url: 'https://status.demiann.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 45 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: portfolio.demiann # unique identifier
    name: demiann.dev
    description: 'Portfolio website'
    url: 'https://demiann.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api.demiann # unique identifier
    name: api.demiann.dev
    description: 'Personal API'
    url: 'https://api.demiann.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: analytics.demiann # unique identifier
    name: analytics.demiann.dev
    description: 'Analytics website'
    url: 'https://analytics.demiann.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: cdn.demiann # unique identifier
    name: cdn.demiann.dev
    description: 'CDN Worker'
    url: 'https://cdn.demiann.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 403 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: cdn.pure # unique identifier
    name: cdn-pure.demiann.dev
    description: 'CDN Worker'
    url: 'https://cdn-pure.demiann.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 403 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: discounted.gg # unique identifier
    name: discounted.gg
    description: 'Discounted.gg frontend'
    url: 'https://discounted.gg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api.discounted.gg # unique identifier
    name: api.discounted.gg
    description: 'Discounted.gg Backend'
    url: 'https://api.discounted.gg/discounts' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: cstools-app # unique identifier
    name: cstools.app
    description: 'CSTools Frontend'
    url: 'https://cstools.app' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cstools.api # unique identifier
    name: api.cstools.app
    description: 'CSTools API'
    url: 'https://cstools.app/api' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: subscroller.app # unique identifier
    name: subscroller.app
    description: 'Subscroller application'
    url: 'https://subscroller.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true