name = "status-page"
workers_dev = true
account_id = "1bda26fe457ea7a9dcd193e268e07770"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

kv_namespaces = [
  { binding = "KV_STATUS_PAGE", id = "14bf59e54bf54520b9f642edb1317b95" }
]

zone_id="fee4c1ef5cc84a9c27bb143ec0bcf6d8"
route="status.demiann.dev/*"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"